# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df0e3657d34a57192a44e806594ed990461557ef04f00959f8fd0aac885564fdff0b203596a96826c7e83f25560eaa4bd8fbfaee1273f5ab95ebd33bd28a132b

test:
  secret_key_base: 76ce4712c350064a317bada541d0f829bcb8692287df81db4b276136d67aa6214982d882cfb365b43b0b2f3a13daf8f3597a2e2b881468c4a6d9bfd8613b9bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
